server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/dwins1/microserviceExample
          search-paths: config-data
          clone-on-start: true
  application:
    name: config-service  